apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: LiquidForce2526
  description: Liquid force component created from GitHub yaml file
  namespace: Production
  tags:
    - service
    - Prod
  links:
    - url: https://example.com/user
      title: Data Dog
    - url: https://example.com
      title: Grafana 
spec:
  type: service
  lifecycle: experimental
  owner: backend-engineering-team
